# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: ci

on:
  release:
    types: [created]

jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Packages
      run: npm ci

    - name: Build Angular SSR
      run: npm run lib:build
    
        
    - run: npm run lib:publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}