# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: ci

on:
  release:
    types: [created]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Packages
      run: npm ci

    - name: Build Angular SSR
      run: npm run lib:build
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Bundle
        path: |
          dist
          package.json

  Publish-To-NPM:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Bundle

      - name: Display Structure of Downloaded Files
        run: ls -R
        
      - run: npm run lib:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}